version: '3'
services:
  node-app:
    container_name: 'node-app'
    # build: .
    build: 
      context: .
      target: development # target environemnt (multi stage)
    volumes:
      - ./src:/app/src:ro
    ports:
      - "3000:4000"
    env_file:
      - ./.env
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    volumes:
      - mongo-db:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
      ME_CONFIG_MONGODB_URL: mongodb://root:123@mongo:27017/
    depends_on:
      - mongo
volumes:
  mongo-db: